# Eureka
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

# Actuator
management:
  endpoints:
    web:
      exposure:
        include: "*"

  # Micrometer Tracing
  tracing:
    sampling:
      probability: 1.0

  # Zipkin
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans
