#eureka config
eureka.client.service-url.defaultZone: http://localhost:8761/eureka

#actuator config
management:
  endpoints:
    web:
      exposure:
        include: "*"


#zipkin config
management.tracing.sampling.probability: 1.0
spring.zipkin.baseUrl: http://loacalhost:9411
